version: '3.8'

services:
  db-postgresql:
    container_name: db-postgresql-crud-container
    hostname: db-postgresql-crud-container
    image: postgres:16.1-alpine
    env_file:
      - ./app-config.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user_backend
      POSTGRES_PASSWORD: password_backend
      POSTGRES_DB: authcruddb
    ports:
      - "5432:5432"
    networks:
      - developer-network
    volumes:
      - postgresql_data:/data/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_backend" ]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 5s

  auth-crud-demo:
    container_name: auth-crud-demo-container
    hostname: auth-crud-demo-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./app-config.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgresql:5432/authcruddb
      - SPRING_DATASOURCE_USERNAME=user_backend
      - SPRING_DATASOURCE_PASSWORD=password_backend
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - "8080:8080"
      - "8787:8787" # DEBUG
    depends_on:
      db-postgresql:
        condition: service_started
    networks:
      - developer-network

networks:
  developer-network:
    driver: bridge

volumes:
  postgresql_data: