spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authcruddb
    username: "${POSTGRESQL_DB_USERNAME}"
    password: "${POSTGRESQL_DB_PASSWORD}"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      #      ddl-auto: create-drop # Deletar e criar uma nova Tabela
      ddl-auto: update # Apenas atualizar a tabela existente com a entity, e adiciona novos campos, caso nao exista
